version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5

  - package-ecosystem: gradle
    directory: "/build-logic"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "chore"
    open-pull-requests-limit: 5
